inventory:
    plugin: SimpleInventory
    options:
        host_file: "inventory/topo1/hosts.yaml"
        group_file: "inventory/topo1/groups.yaml"
        defaults_file: "inventory/topo1/defaults.yaml"
runner:
    plugin: threaded
    options:
        num_workers: 100